<?php

namespace Orange\SearchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityToIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityToIndexRepository extends EntityRepository
{

    public function isToIndex($className)
    {   
        $entity = $this->findOneByClassName($className);
        if ($entity) {
            return $entity->getToIndex();
        } else {
            return false;
        }
    }
    
    public function findEntityToIndexClassNames()
    {
        $classNames      = array();
        $entitiesToIndex = $this->findByToIndex(true);
        
        foreach ($entitiesToIndex as $entity) {
            $classNames [] = $entity->getClassName();
        }
        return $classNames;
    }
    
    
}
