<?php

namespace Orange\SearchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SyncIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyncIndexRepository extends EntityRepository
{
}
